version: '3'

services:
  service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  
  mysql:
    image: mysql:latest
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: password  # Change this to your desired root password
      MYSQL_DATABASE: ganjababydb  # Change this to your desired database name
    volumes:
      - ./mysql_data:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service

volumes:
  mysql_data:
