version: '3'

services:
  service:
    image: manav108/mahalaxmi:latest
    ports:
      - "8000:8000"
  
  nginx:
    image: manav108/mahalaxmi-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - service

