version: '3'

services:
  service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - service

